using Android.Content.PM;
using Android.OS;
using Android.Views.Animations;
using AndroidX.ConstraintLayout.Core.Widgets.Analyzer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static Android.Print.PrintAttributes;
using static Android.Provider.ContactsContract.CommonDataKinds;
using static Android.Renderscripts.ScriptGroup;

namespace MurderMystery.Generators
{
    public class ActStrongWords
    {
        public List<string> Act1 = new List<string>()
        {
            "Intrigue",
            "Suspicion",
            "Tension",
            "Mysterious",
            "Enigmatic",
            "Puzzling",
            "Confounding",
            "Cryptic",
            "Baffling",
            "Curious",
            "Perplexing",
            "Uncanny",
            "Eerie",
            "Unsettling",
            "Foreboding",
            "Ominous",
            "Menacing",
            "Sinister",
            "Threatening",
            "Intimidating",
            "Startling",
            "Shocking",
            "Surprising",
            "Astonishing",
            "Unpredictable",
            "Enthralling",
            "Captivating",
            "Fascinating",
            "Compelling",
            "Gripping",
            "Engrossing",
            "Absorbing",
            "Spellbinding",
            "Entrancing",
            "Alluring",
            "Seductive",
            "Enchanting",
            "Beguiling",
            "Mesmerizing",
            "Hypnotic",
            "Chilling",
            "Haunting",
            "Terrifying",
            "Frightening",
            "Petrifying",
            "Spine-tingling",
            "Creepy",
            "Macabre",
            "Grim",
            "Dark"
        };
        public List<string> Act2 = new List<string>()
        {
            "Clues",
            "Red herrings",
            "Revelations",
            "Twists",
            "Turns",
            "Shockers",
            "Bombshells",
            "Startling discoveries",
            "Startling revelations",
            "Key pieces of evidence",
            "Hints",
            "Foreshadowing",
            "Suspicious behavior",
            "Alibis",
            "Motives",
            "Accusations",
            "Betrayals",
            "Deceptions",
            "Misdirection",
            "Hidden agendas",
            "Shifting alliances",
            "Secret meetings",
            "Covert operations",
            "Undercover investigations",
            "Dangerous liaisons",
            "High-stakes gambles",
            "Daring risks",
            "Bold moves",
            "Strategic planning",
            "Uncovering the truth",
            "Seeking justice",
            "Navigating danger",
            "Narrow escapes",
            "Close calls",
            "Heart-pumping action",
            "Intense confrontations",
            "Dramatic showdowns",
            "Deadly threats",
            "Rising tensions",
            "Mounting pressure",
            "Increasing stakes",
            "Heightened urgency",
            "Race against time",
            "Desperate measures",
            "Life and death decisions",
            "Ethical dilemmas",
            "Moral quandaries",
            "Consequences",
            "Resolutions",
            "Closure"
        };
        public List<string> Act3 = new List<string>()
        {
            "Reveals",
            "Solutions",
            "Climax",
            "Final showdown",
            "Culmination",
            "Unmasking",
            "Confessions",
            "Accusations",
            "Confrontations",
            "Consequences",
            "Resolution",
            "Justice",
            "Redemption",
            "Retribution",
            "Punishment",
            "Closure",
            "Relief",
            "Satisfaction",
            "Enlightenment",
            "Epiphany",
            "Revelation",
            "Catharsis",
            "Release",
            "Redemption",
            "Triumph",
            "Victory",
            "Loss",
            "Mourning",
            "Grief",
            "Regret",
            "Guilt",
            "Forgiveness",
            "Mercy",
            "Compassion",
            "Understanding",
            "Empathy",
            "Closure",
            "Moving on",
            "Renewal",
            "Transformation",
            "Growth",
            "Change",
            "Acceptance",
            "Healing",
            "Hope",
            "Happiness",
            "Joy",
            "Love",
            "Gratitude",
            "Peace"
        };
    }
}
